# '''
# Define las variables de entorno SIGEFVE_BIND_BASE_PATH y SIGEFVE_WEB_PORT para poder iniciar el proyecto.
# SIGEFVE_BIND_BASE_PATH = ruta a la carpeta donde se clona el proyecto.
# SIGEFVE_WEB_PORT = puerto para el servidor web.
# '''
services:
  sigefve_frontend:
    hostname: sigefve_frontend
    container_name: sigefve_frontend
    image: debian:12.1
    ports:
      - "${SIGEFVE_WEB_PORT}:80"
    restart: unless-stopped
    command:
      - /bin/bash
      - -c
      - |
        export DEBIAN_FRONTEND=noninteractive
        ln -snf /usr/share/zoneinfo/America/Mexico_City /etc/localtime && echo America/Mexico_City > /etc/timezone
        apt -y update
        apt install -y apache2
        service apache2 start
        tail -F keep.alive
    volumes:
      - ${SIGEFVE_BIND_BASE_PATH}/web-app:/var/www/html

  sigefve_python:
    hostname: sigefve_python
    container_name: sigefve_python
    image: debian:12.1
    ports:
      - "8822:5001"
    restart: unless-stopped
    command:
      - /bin/bash
      - -c
      - |
        export DEBIAN_FRONTEND=noninteractive
        ln -snf /usr/share/zoneinfo/America/Mexico_City /etc/localtime && echo America/Mexico_City > /etc/timezone
        apt -y update
        apt install -y python3 python3-pip python3-venv
        pwd
        which python3
        which pip3
        cd /python
        python3 -m venv python/venv
        source python/venv/bin/activate
        pip3 install flask flasgger requests
        python3 app.py
        tail -F keep.alive
    volumes:
      - ${SIGEFVE_BIND_BASE_PATH}/python:/python

  sigefve_java:
    hostname: sigefve_java
    container_name: sigefve_java
    image: debian:12.1
    environment:
      - DB_URL:jdbc:postgresql://postgresql_java:5432/sigefve
      - DB_USER:data
      - DB_PASSWORD:data
    ports:
      - "${JAVA_PORT}:8585"
    restart: unless-stopped
    depends_on:
      - postgresql_java
    command:
      - /bin/bash
      - -c
      - |
        export DEBIAN_FRONTEND=noninteractive
        ln -snf /usr/share/zoneinfo/America/Mexico_City /etc/localtime && echo America/Mexico_City > /etc/timezone
        apt -y update > /dev/null 2>&1
        apt install -y default-jdk > /dev/null 2>&1
        java -version
        date
        cd /root/java

        echo version 0.2
        javac -d out -cp .:jar/gson-2.11.0.jar:jar/postgresql-42.7.8.jar com/sigefve/ServidorHTTP.java
        javac -d out -cp .:jar/gson-2.11.0.jar:jar/postgresql-42.7.8.jar com/sigefve/utils/InicializadorDatos.java
        java -cp .:out:jar/gson-2.11.0.jar:jar/postgresql-42.7.8.jar com.sigefve.ServidorHTTP
        : java -cp .:out:jar/gson-2.11.0.jar:jar/postgresql-42.7.8.jar com.sigefve.utils.InicializadorDatos

        tail -F keep.alive
    volumes:
      - ${SIGEFVE_BIND_BASE_PATH}/java:/root/java

  postgresql_java:
    hostname: postgresql_java
    container_name: postgresql_java
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 54302:5432
    volumes:
      - ${SIGEFVE_BIND_BASE_PATH}/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sigefve

  sigefve_go:
    hostname: sigefve_go
    container_name: sigefve_go
    image: debian:12.1
    ports:
      - "${SIGEFVE_GO_PORT}:8080"
    restart: unless-stopped
    # environment:
    #   - PATH=/usr/local/go/bin:PATH
    command:
      - /bin/bash
      - -c
      - |
        export DEBIAN_FRONTEND=noninteractive
        ln -snf /usr/share/zoneinfo/America/Mexico_City /etc/localtime && echo America/Mexico_City > /etc/timezone
        apt -y update
        apt install -y wget locate
        wget https://go.dev/dl/go1.25.4.linux-amd64.tar.gz
        rm -rf /usr/local/go && tar -C /usr/local -xzf go1.25.4.linux-amd64.tar.gz
        export PATH=/usr/local/go/bin:$$PATH
        pwd
        updatedb
        locate router.go
        cd go
        go run main.go
        tail -F keep.alive
    volumes:
      - ${SIGEFVE_BIND_BASE_PATH}/go:/go
